server:
  error:
    include-message: always
  port: 8770

spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: NON_EMPTY
    serialization:
      indent_output: false
      write_dates_as_timestamps: false
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    deserialization:
      adjust_dates_to_context_time_zone: false
      fail_on_unknown_properties: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${foodService.db.url}
    username: ${foodService.db.username}
    password: ${foodService.db.password}
  flyway:
    enabled: true
    url: ${foodService.db.url}
    username: ${foodService.db.username}
    password: ${foodService.db.password}
    schemas: ${foodService.db.schema}
    placeholders.foodServiceName: ${spring.application.name}
  rabbitmq:
    host: ${foodService.rabbit.host}
    port: ${foodService.rabbit.port}
    username: ${foodService.rabbit.username}
    password: ${foodService.rabbit.password}

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
retry:
  maxAttempts: 2
  maxDelay: 1000