foodService:
  db:
    username: postgres
    password: 1z2x3c4v
    url: jdbc:postgresql://localhost:8098/foodService
    schema: public
  rabbit:
    host: localhost
    port: 5672
    username: admin
    password: 1q2w3e4r
service:
  rabbit:
    queueGetOrderIn: foodSGetOrder.IN
    queueNewOrderIn: foodSNewOrder.IN
    queueGetMenuIn: foodSGetMenu.IN
    queueGetAllMenuIn: foodSGetAllMenu.IN
    queueGetRestIn: foodSGetRest.IN
    routingKeyGetOrderIn: toFoodServiceGetOrderIn
    routingKeyNewOrderIn: toFoodServiceNewOrderIn
    routingKeyGetMenuIn: toFoodServiceGetMenuIn
    routingKeyGetAllMenuIn: toFoodServiceGetAllMenuIn
    routingKeyGetRestIn: toFoodServiceGetRestIn
    routingKeyErr: foodServiceErr
    queueErr: foodService.ERR
    queueOut: foodService.OUT
    routingKeyOut: toFoodServiceOut
    exchange: foodS.ex
restaurants:
  names:
    - Charlie
    - kfc
    - Holostyak