server:
  port: 8737

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${restaurant.db.url}
    username: ${restaurant.db.username}
    password: ${restaurant.db.password}
  flyway:
    enabled: true
    url: ${restaurant.db.url}
    username: ${restaurant.db.username}
    password: ${restaurant.db.password}
    schemas: ${restaurant.db.schema}
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000